### ISSUE TITLE
Search Not Returning All Results

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#110]
# Reporting new issue for Commerce Hub

**Page**
Search https://dev-developer.fiserv.com/search/
Search https://stage-developer.fiserv.com/search/
Search https://developer.fiserv.com/search/

**Describe the bug**
When searching in Dev only results with the word in the title come back. Example searching error should result in multiple articles but only shows 2, searching for paymentCard returns no results.

Searching in Stage returns no results

**To Reproduce**
Go to search and use the term error or search for a specific field like paymentCard

**Expected behavior**
Search should return all articles that have the word searched

**Screenshots**
![image](https://user-images.githubusercontent.com/75692745/157753653-2ef00d6a-55ad-41b4-bf58-aa3282882143.png)

**Comment by wwfiserv** [comment]
@OZ-FS @acho-fiserv @TaniaSarkar89

**Comment by wwfiserv** [comment]
Appears to only impact PROD right now, search may return a result but doesn't pull the title instead uses the markdown file name.
![image](https://user-images.githubusercontent.com/75692745/164052090-04f1826e-9c83-4edb-ac4b-773205232a82.png)

**Comment by TaniaSarkar89** [comment]
@wwfiserv  this issue has been fixed in our lower environments like Stage: 
![image](https://user-images.githubusercontent.com/74629095/164073451-e98abc05-7ef4-4b35-90cd-9d2cb58a36ea.png)

But unfortunately we had some production deployment issue last Thursday(04/14) so our code changes were not pushed in production. The code changes would be promoted as part of our next production release on 04/28.
Linking JIRA ticket here for reference: https://firstdatateam.atlassian.net/browse/PORT-3715

**Comment by sfiserv** [comment]
@TaniaSarkar89 the production is now fixed in Production too.
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/87097017/168002327-8d2be10a-b6cf-4132-b953-461263109082.png">
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/87097017/168002640-1ed6626c-1489-4403-bc87-7eabf3a78753.png">
