### ISSUE TITLE
Lef Nav Highlight Bug

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#145]
# Reporting new issue for Commerce Hub

**Page**
Left Navigation

**Describe the bug**
The left nav is not updating based on article you are in when navigating from the main CH landing page.

**To Reproduce**
Example selecting apple-pay in-app from the CH landing page takes yo uto the article but does not display where you are. If you navigate to apple-pay in-app from anywhere else it displays correctly.

**Expected behavior**
Regardless of entry point the left nav should highlight where the user is.

**Comment by sfiserv** [comment]
Jira ticket has been created for this issue 
https://firstdatateam.atlassian.net/browse/PORT-4538

**Comment by anandrewfiserv** [comment]
Partial fix remaining. Ticket: https://firstdatateam.atlassian.net/browse/PORT-4730

**Comment by sfiserv** [comment]
This issue has been fixed in dev env ( PORT-4730) closing this issue.
https://dev-developerstudio.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/Wallets-AltPayments/Apple-Pay/Apple-Pay.md&branch=develop
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/87097017/182936952-1ba41b70-9c20-46f4-9293-f860fa65268e.png">
