### ISSUE TITLE
Search Should Maintain Filters

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#148]
**Page**
Search

**Describe the bug**
When you leave the search results and click back it doesn't maintain the previous filtering.

**To Reproduce**
Search for any term and filter to Commerce Hub. Select an article. Click the back button to return to search results.

**Expected behavior**
Search should persist the filtering so a client does not need to continually refilter the results when they are looking for an article.

**Comment by sfiserv** [comment]
jira ticket is created to track this issues
https://firstdatateam.atlassian.net/browse/PORT-4449

**Comment by sfiserv** [comment]
This is currently worked in in sprint 14

**Comment by jimmychen-fiserv** [comment]
Consider about the severity and priority, this ticket will not be fixed at this point.

**Comment by minh-pham1** [comment]
This enhancement has been added to our dev environment as part of our site redesign. It'll move up to production in the near future. Thank you for your patience!

**Comment by wwfiserv** [comment]
@minh-pham1 any update, marked stale

**Comment by minh-pham1** [comment]
Hello @wwfiserv! I noted that the change were live on our develop environment in the new content page on 3/11 (meaning you can test it on QA).

That being said, I think the functionality should also be functional on the current version of search on stage/prod since we made changes for the URL to be tracking all the filters. Could you have a look and see if this is true?

I do note that there is an issue where the loading of the product filters are delayed so it doesn't properly render the checkmark despite the product filter still being active (i.e. applying the "Commerce Hub" filter, clicking a result, then clicking back will still keep the search results filtered despite the "Commerce Hub" checkbox not being checked).
