### ISSUE TITLE
Accessing the response header details on the portal

### ISSUE THREAD

**Issue by AwaneeshSrivastava** [Fiserv/Support#152]
**Region** (optional)
APAC

**Is your feature request related to a problem? Please describe.**
For our FirstVision-APAC API we are introducing the pagination logic by using the two  response header fields  to pass the information of 
a)	Flag to indicate if more data is available 
b)	paginationKey to use in the subsequent request 

**Describe the solution you'd like**
We want the means by which the response header is accessible on the portal. 

**Describe alternatives you've considered**
None

**Additional context**
This feature is available in any testing tool like postman where it allows viewing the response header along with the response message.

**Comment by sfiserv** [comment]
JIra is created https://firstdatateam.atlassian.net/browse/PORT-4446 to track this issue.

**Comment by TaniaSarkar89** [comment]
Prioritizing this ticket for the next Sprint 14.
Cc: @rajeshb15

**Comment by TaniaSarkar89** [comment]
@AwaneeshSrivastava  which API can we use to test this ?

**Comment by AwaneeshSrivastava** [comment]
You can test using "List Transaction" API under the Account Management group within FirstVision-APAC.  In the response header, there will be two header pertaining to pagination. These two headers are (isContinued and continuationToken).
![image](https://user-images.githubusercontent.com/91457011/185530822-c3ccdc22-50d0-4739-9d78-37af1339343c.png)

**Comment by TaniaSarkar89** [comment]
Hi @AwaneeshSrivastava just wanted to give you an update on this ticket, we have started working on this enhancement and it will take us few more sprints to complete this entirely. Apologize for the delay we are a small team now and have our hands full in resolving few high priority issues for our upcoming production release.

However following scenario calls for some consideration.
The requirement for this ticket is whenever a user hits the Run button, only then he would see the Response Headers on the UI. 
But we were also thinking of a scenario when a user DOES NOT hit the Run button but still wants to view the Response Headers... That's why we are encouraging you to add the response headers in the spec file like below for this default scenario:

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/74629095/186490640-b60bc579-c9b9-4d44-823b-9b03ec2980fc.png">

[Reference: https://swagger.io/docs/specification/describing-responses/]

For now we decided that if we do not find the response headers in the spec files then we would probably display nothing inside the response header tab on UI.

Please let us know your thoughts on the same.

Thanks! 

Cc: @acho-fiserv @bigsauron @sfiserv

**Comment by sfiserv** [comment]
The back end changes have been implemented. The UI changes will be implemented as part of Sprint 18 - MIlestone 18
https://firstdatateam.atlassian.net/browse/PORT-4900

**Comment by sfiserv** [comment]
Closing this issue as there is no response on the Client verification from client.
