### ISSUE TITLE
Request for new feature to mark API  Internal/External

### ISSUE THREAD

**Issue by ronirajan-fd** [Fiserv/Support#177]
Is there any way we can mark some APIs internal external with OpenAPI extensions that can be used by Developer studio team to decide if they should show this in client facing env. or not?  is something similar already available? 

Our team is adding below tag in hope we can use to differentiate.  
x-api-scope: Internal

See comments on OpenAPI spec request. They believe this is something can be used done with extensions and the responsibility taken on the devleoper portal implementation to show/hide or control access. 
https://github.com/OAI/OpenAPI-Specification/issues/433

**Comment by adamaltman** [comment]
@ronirajan-fd this isn't part of the spec currently, and it's not clear that it should be. There are solutions in the market that solve this using specification extensions -- more or less like your `x-api-scope: internal`. 

See this for an example of one: https://redocly.com/docs/cli/guides/hide-apis/

**Comment by BillyBolton** [comment]
I would like to see more granularity than just internal/external since this assumes there are only two types of visibility. I've had a use-case where I need to dynamically expose endpoints based on where the specification is being deployed to, so using `hidden`, or the possibility of `internal/external` would not suffice. There are three separate environments I need to consider, for example.

There's a couple comments I'd like to contribute for this issue.

I've implemented a rather verbose way to dynamically hide/expose operations using extensions but the level of pre-processing that is required is quite expensive. I can't share the code but basically I decorate the Operation model using extensions, which I then scrub from the spec's Path/PathItem based on the extension's value vs deployment environment using the `OpenApiCustomiser`. Once this extension is used for this scrubbing, I then remove the extension from the operation since it is only needed internally.

OpenAPI unfortunately only offers customizers for `OpenApiBuilderCustomiser`, `OpenApiCustomiser`, `OperationCustomizer`, `ParameterCustomizer`, and `PropertyCustomizer`. These customizers are great for pre-processing _prior_ to generating the spec. There are cases, however, that other components such as definitions/`Schemas`, `tags, etc. need to also be hidden when they are not referenced by other _now hidden_ components. So scrubbing needs to be done recursively _after_ the spec has been generated. If customizers were available for all components in the OAS, and especially for `Paths` and `Schemas`, then this scrubbing could be done more efficiently.
