### ISSUE TITLE
Needs to show loader Icon when pressing Download Postman collection

### ISSUE THREAD

**Issue by eliascanaza** [Fiserv/Support#229]
# Reporting new issue for [NAME] (Tenant/Product)

**Region** (if applicable)
EMEA and NA

**Page**
[Path of the page where the problem exists.](https://developer.fiserv.com/product/IssuerSolutions/api/?type=post&path=/payments/v2/initiateDemandAchPayment&branch=develop&version=1.0.0)

**Describe the bug**
When at first times I am pressing **Download Postman collection** is giving me error: **Failed - Server problem**, but after wait some time that is working normal, we need to add some loader icon. The problem is in every endpoint page.

**Expected behavior**
Must to display an loader icon when pressing **Download Postman collection**

**Screenshots**
![image](https://user-images.githubusercontent.com/1819754/201211065-f794b3c6-3854-4e6a-b5e4-eb3a0e401a96.png)

**Comment by jimmychen-fiserv** [comment]
https://firstdatateam.atlassian.net/browse/PORT-5458

**Comment by sfiserv** [comment]
@eliascanaza  this feature has been implemented. please verify in the dev env.

**Comment by eliascanaza** [comment]
Hi @sfiserv , I tested on dev env, and I can see the next details:

1. the load icon is showing around 5 seconds
2. after that time still I am getting Failed - Server problem, as you see in the image
3. I wait some time and I pressed again and still after the load icon is getting the same error

I consider the ticket is not close yet, because the error that I am getting.

<img width="1289" alt="image" src="https://user-images.githubusercontent.com/1819754/208685638-6d394169-d883-4808-8b5c-98172905b95d.png">

**Comment by minh-pham1** [comment]
Hello elias!

The solution that was implemented was simply a time-based lockout so that users know that they _have_ sent the request to download API (greying out the download link and putting a spinner) for ~3 seconds. The loading icon doesn't actually check your download request and browser's download progress.

We will look into the issue underlying the download failure (we're not sure if it's failing due to multiple requests concurrently, duplicate requests overlap, timing, server, etc.). For now, please just treat the loading icon to indicate that you have initiated a download and wait for the download to finish before attempting another one.

**Comment by sfiserv** [comment]
Tracking this issue in https://firstdatateam.atlassian.net/browse/PORT-5729

**Comment by sfiserv** [comment]
Downloading issue has been fixed and deployed to production.
