### ISSUE TITLE
Unable to reset Developer Studio Password

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#284]
# Reporting new issue for Fiser Developer Studio

I'm unable to reset the Developer Studio account password. Whenever I enter the One-time passcode (OTP) received via email to reset the password, it throws incorrect OTP error all the time.
![image](https://user-images.githubusercontent.com/81968767/214285769-428b2b7f-0c68-40e7-9628-09727af4149d.png)

**Comment by minh-pham1** [comment]
Hello Akshay! Our portal has various password requirements, one of which does not allow the re-usage of recent passwords (the system keeps a history of multiple recent passwords, not just the last one). I believe in this case, your OTP is correct but you are reusing a recent password (based on the `The password cannot be reused` requirement being greyed out).

We wrapped both errors into one statement initially for brevity but we'll separate them out to improve clarity. Thank you for bringing it to our attention!

**Comment by sfiserv** [comment]
@minh-pham1 based on your comments/clarification marking this ticket as done/won't fix.

**Comment by fiservakshay** [comment]
Hi @minh-pham1, Thanks for your reply and suggestions. 

This time, I tried using very different password, but whenever I click **Submit**, at first it throws error message: "Something went wrong, please try again". And then it throws "incorrect password ..." error message all the time.

Wondering if anyone else can able to reset the password. 

![image](https://user-images.githubusercontent.com/81968767/214499531-14da8baa-4d58-46b9-9ed0-46315afe129d.png)

cc: @sfiserv

**Comment by sfiserv** [comment]
@fiservakshay Is this issue related to any particular environment like dev, qa, stage. 
It there a possibility that you might be reusing the password from the last few resets?

**Comment by minh-pham1** [comment]
Hello Akshay!

Sorry to hear that you're still having issues. The "something went wrong" prompt does occur from time to time since the authentication service comes from another provider and is not something we personally control. Unfortunately, I cannot replicate this behavior on the dev environment with my own account nor the qa account.

Is it possible to try using security questions instead (I know that you may not have had a chance to set it up yet so it might not be usable)? Otherwise, there's a _small_ chance that despite the "Something went wrong" message the password did update to the new one you provided. If it continues to not work, please let us know which environment you're encountering this issue on and we'll consult with the relevant engineers to see if it's possible to somehow force a password reset or any other viable solution.

**Comment by fiservakshay** [comment]
I am facing this issue in **Dev** environment. I tried using combination of password that I would never use but still facing the same issue.

Also, I checked and looks like I did not set security question :(

**Comment by fiservakshay** [comment]
I cleared browser cache and  cookies still experiencing the same issue. I am unable to create new account using Fiserv email and DevStudio does not accept personal email.

I need access to check the functionality and write documentation accordingly. Can you please reset my email so that I will be able to register.
This is very important.

**Comment by fiservakshay** [comment]
Able to create account in QA environment. Hence closing the ticket.
