### ISSUE TITLE
Sandbox integration firstvision-latam

### ISSUE THREAD

**Issue by leonardotorresfiserv** [Fiserv/Support#300]
product: https://github.com/Fiserv/firstvision-latam

We would like to integrate our developer studio with our sandbox environment. Our current sandbox integration has a URL exposed to the internet, which is configured in the API portal. Clients provide an "API key" header to gain authorization to consume our APIs. Currently, we generate the API key in Apigee and share it with clients via email.

Our api product is: latam-gfs-sandbox
api proxy: latam-gfs-sandbox

The process for creating the API key involves creating a new app in Apigee, assigning the product to the app, and then generating the API key. For these apps, we use custom attributes. Is this supported by your end system?

![screenshot_apigee](https://user-images.githubusercontent.com/124207478/217623344-04eacb3c-54dc-4bf3-936b-6db9f6eec56a.png)

**Comment by sfiserv** [comment]
created a tracking ticket for this issue https://firstdatateam.atlassian.net/browse/PORT-5825

**Comment by TaniaSarkar89** [comment]
Hi @leonardotorresfiserv  @CinthyaRivera,
As discussed earlier, it was advised to move on with the prism mock server strategy because of the urgency of the demo on February 22nd and we have enable the prism mock server for "FirstVision-LATAM".
In the next sprint let's start the conversations around **Workspaces** (where users can create api key & credentials) & **Live sandbox**.
