### ISSUE TITLE
[SUPPORT]: Require 'Native' 3D-Secure Integration Method for Sandbox

### ISSUE THREAD

**Issue by SamraatBansal** [Fiserv/Support#304]
**Region** (optional)
North America (US and Canada)

**Is your feature request related to a problem? Please describe.**
I want to integrate the 3D-Secure payment method using REST API Calls, I am not able to do so as Fiserv has not provided the access to Native integration method of 3D secure.

**Describe the solution you'd like**
I want to be able to have access around 3D Secure integration method with 'Native' flow of Fiserv, I am working with a Payment Orchestrator which connects wide set of merchants to Payment Gateway. 
We have completely Open Sourced our product [https://github.com//juspay/hyperswitch](HyperSwitch).
We are looking for fast action resolution for this, so that integration can be completed at the earliest.

**Additional context**
<img width="1087" alt="Screenshot 2023-02-10 at 1 13 28 PM" src="https://user-images.githubusercontent.com/55536657/218032071-446bb9a6-96f8-4a3c-ab1f-0adc1aacbf1f.png">

**Comment by wwfiserv** [comment]
@SamraatBansal we are currently developing our 3D-Secure models and should be ready in late Q2. I'm unsure if you are looking for the right integration, what Gateway are you currently working with? Commerce Hub is designed for Enterprise clients and is currently still developing features. We have not started allowing implementation for payment facilitators or vendors.

**Comment by SamraatBansal** [comment]
Hi @wwfiserv 
Thank you for response to the query.

We are integrating ‘Commerce Hub’ itself, We want a solution where the Gateway can perform 3DS 2.0 Verification i.e. When we provide card details you can respond with a redirect url where the user can authorise the payment and complete the 2FA.

I believe the Native

**Comment by wwfiserv** [comment]
@SamraatBansal correct this will be our Native integration using Cardinal commerce as an added solution. Once we have it designed it will be available in Dev Studio to preview, however the sandbox will take some additional time to simulate responses.

I would also recommend if you are working for a merchant that they contact their account representative to ensure that Commerce Hub is a viable product for them, because as I mentioned before it is limited to Enterprise merchants.
