### ISSUE TITLE
Change tab is not possible

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/Support#338]
# Reporting new issue for [TAB] (First Vision LATAM)

**Region** (if applicable)
LATAM

**Page**
Path of the page where the problem exists.

**Describe the bug**

**To Reproduce**
1. Go to https://qa-developerstudio.fiserv.com/product/FirstVisionLATAM/docs/?path=docs/english/api-reference/1-account.md&branch=develop
2. Click on Second tab
3. See error

**Expected behavior**
Visualize information with second tab.

**Screenshots**
![image](https://user-images.githubusercontent.com/111396588/224469516-d28089ae-7c94-4c81-9b41-74565e275f08.png)

**Desktop (please complete the following information):**

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by minh-pham1** [comment]
This issue is due to our markdown parsing not being designed to handle non-English characters. Unfortunately our engineers are a bit swamped right now but we are aware that this tabs issue does block the ability to read the content entirely at the current moment and will try to address it soon.

The issue comes from when tabs and right navigation have ¿ or characters with accent marks (ó, é, etc.) in them. We'll have to see how best to format the page navigation to accommodate for this issue. Sorry for the inconvenience!

**Comment by CinthyaRivera** [comment]
Ok, I'll keep pending for updates

**Comment by sfiserv** [comment]
https://firstdatateam.atlassian.net/browse/PORT-6076. tracking ticket for this issue.

**Comment by sfiserv** [comment]
@CinthyaRivera please validate the fix on dev env.

**Comment by CinthyaRivera** [comment]
@sfiserv I validated on QA and still same issue

**Comment by sfiserv** [comment]
@CinthyaRivera I understand and apologies. We have a freeze on on our deployments and also locked down on the dev env hence you will be able to verify the changes once we resume our deployment process.

**Comment by sfiserv** [comment]
@CinthyaRivera can you please review the QA env for the changes.

**Comment by CinthyaRivera** [comment]
@sfiserv Validated on QA and it's fixed. Thanks for your support :D

**Comment by sfiserv** [comment]
closing this ticket as verified from client.
