### ISSUE TITLE
Exchange API Versioning issue 

### ISSUE THREAD

**Issue by up-t-j** [Fiserv/Support#383]
# Reporting new issue for Exchange

**Region** 
API Explorer
**Page**
Exchange product page /api explorer

**Describe the bug**
We are attempting to a new version of the API specs, and want to have this available at the same time as the previous 2.0.0 specs as there are some new endpoints in 3.0.0 that aren't in 2.0.0, and some old endpoints that have no changes. I was able to get this to work briefly but then stopped.

It appears these are parsing through the github validator correctly, but are not showing on the dev studio as expected - and have been informed they are not parsing on the backend correctly.
being supported by tania at the moment. please let me know if we need any additional details

**To Reproduce**
Currently not viewable on API Explorer, APIs not behaving consistently - some times some endpoints do not show and swap versions

**Expected behavior**
Expected behaviour is that 2.0.0 APIs should be viewable along with 3.0.0 APIs. 
New endpoints that exist in 2.0.0 should be swappable, 2.0.0 endpoints that do not exist in 3.0.0 should still be visible, 3.0.0 endpoints that dont exist in 2.0.0 should be visible. 

**Screenshots**

![image](https://user-images.githubusercontent.com/102667658/234597930-ce9f1de7-47ff-402c-8468-31a8a1f3cd60.png)

**Desktop (please complete the following information):**
 - Browser Chrome 
**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Additional context**
@TaniaS-fiserv 
cc @sfiserv

**Comment by TaniaS-fiserv** [comment]
Hi @up-t-j,  the problem was stemming from the api-3.0.0.yaml file due to a circular schema dependency in one of the schemas. So "TransactionInstructionDetailedIns" schema points to "**AccountDetailsDTO**" schema which refers to "**split_details**" referring back to "**TransactionInstructionDetailedIns**". so "**split_details**" is spawning a circular dependency here.

Please note that while troubleshooting this problem I had cloned and renamed the original api-3.0.0.yaml file to [api-3.0.0-original.yaml](https://github.com/Fiserv/exchange/blob/develop/reference/3.0.0/api-3.0.0-original.yaml) and removed some of the endpoints in my test file [api-3.0.0.yaml](https://github.com/Fiserv/exchange/blob/develop/reference/3.0.0/api-3.0.0.yaml). Please add the necessary endpoints to the file and Kindly take a look at this endpoint `/funding/detailed-instruction` to remove circular dependency as its often a bad design. 

For now I have commented out the reference of **split_details** from **AccountDetailsDTO** schema definition. I have also re-run the api indexing job for 'Exchange' in the QA env so that you can verify the same at your end. 

![image](https://user-images.githubusercontent.com/74629095/235791219-ecca41f0-7ab9-4a11-89c0-1611a392b13a.png)

Since no action is required from our end, hence closing this ticket.

 Thanks!
 
 Cc: @sfiserv
