### ISSUE TITLE
START

### ISSUE THREAD

**Issue by alok-kumar2** [Fiserv/Support#391]
### Name of your product / tenant

START

### Type of Tenant

- [X] Full service
- [X] Doc only
- [X] Link out

### Team Members

alok-kumar2/alok.kumar2@fiserv.com

### Bug Reporting

alok-kumar2/alok.kumar2@fiserv.com

### Feedback Reporting

alok-kumar2/alok.kumar2@fiserv.com

### Enhancement Reporting

alok-kumar2/alok.kumar2@fiserv.com

### Internal tenant

No

### Product of Carat

No

### Merchants solution area

Yes

### Customer Segments for Merchants

- [ ] SMB
- [ ] Enterprise

### Financial Institutions solution area

Yes

### Customer Segments for Financial Instituitions

- [ ] Bank
- [ ] Credit Union
- [ ] Large Financial Institution

### Fintech solution area

Yes

### Region of Operation

- [X] North America
- [ ] EMEA
- [ ] LATAM
- [ ] APAC

### RESTful

Yes

### SDK

Yes

### Runbox

Yes

### Mock Sandbox

Yes

### Live Server

Yes

**Comment by sfiserv** [comment]
@alok-kumar2  is this a test ticket ?

**Comment by alok-kumar2** [comment]
No This is not test. We need to build Tenants for Developer Studio.

**Comment by sfiserv** [comment]
@alok-kumar2 
The request raised here does not provide  correct requirements from you. Seems you have checked everything as a requirement. 

- Please provide the full qualified Fiserv name of your product. It should align with the Fiserv product name. Provide an existing developer portal/ Fiserv Product page if you have one.

- You can choose only one Tenant type. Full or Linkout tenant 

- Please reconfirm the Category does you product fall under.

- We can only enable only one either Mock or Live Server

- Please read our documentation to understand the various sections in this on boarding form and Fiserv Developer Studio as a product.     **https://fiserv.gitbook.io/tenant-docs/**

We are closing this ticket due to several issues. Please open a new request with correct requirements for your product.
