### ISSUE TITLE
Spec Portal QA Access

### ISSUE THREAD

**Issue by kcaramat** [Fiserv/Support#397]
### Operating system

N/A

### Laravel Version

N/A

### PHP Version

N/A

### Project Location

Local

### Bug description

Admin access needed to Spec Portal in QA. Currently, can't access any markdown files or documents.

**Comment by sfiserv** [comment]
@kcaramat this issue is happening due the access/permission assigned to the Doc/files as private. hence the user is not able to access the doc without exclusive permissions. The files which are public are accessible and clickable.
That said we are also verifying the user flow decided to handle the Private, as whether we completely hide those private docs or we inform the user as what are the next steps.

**Comment by kcaramat** [comment]
@sfiserv, when I'm logged into QA I can't click on Public docs either.
