### ISSUE TITLE
API explorer unavailable whenever API swagger is updated

### ISSUE THREAD

**Issue by shubhamKanse99** [Fiserv/Support#435]
### Product

firstvision-emea

### Page

Home

### Description

Everytime we update the swagger document APi explorer throws this error 
![image](https://github.com/Fiserv/Support/assets/117971606/d8e45fce-1570-4f33-affd-d11c602b8aa1)

This directly impacts clients who are referring API swagger for development

please help resolve this urgently!

### Expected Behaviour

API explorer should not crash.

### Operating system

NA

### Browser

NA

### Region

EMEA, APAC

**Comment by sfiserv** [comment]
@shubhamKanse99  we will be have our team reindex the Production env on thursday which will fix the issue.

**Comment by StevenPorterFiserv** [comment]
As I am sure you understand, not having access to the API documentation is really painful for our client’s and their developers. As a customer facing “Front Door” to Fiserv products, it’s unavailability reflects really badly on us. Given the number of issues and queries being raised by affected clients (including multiple from different development teams under a single client), it is obviously negatively impacting client confidence in our FirstVision API solution and ‘likelihood to recommend’, as well as wasting our client service team’s time having to deal with the queries it is generating. 

If this is something our team are doing wrong with our implementation, then please do not hesitate to guide us how we can improve to avoid this issue in the future - as this seems to affect our version of the portal every time we update production following a release. It has reached the point where we have started providing clients with [instructions to work around the issue](https://escmconfluence.1dc.com/display/EMEAAPI/Working+around+issues+in+the+Developer+Studio+to+view+Swagger) and reference the swagger directly in Github using [Swagger Editor](https://editor.swagger.io/) instead, which is far from ideal and really does not reflect well on us as a technology company.

If this re-indexing runs at a certain time (i.e. Every 6am EST Thursday), please let us know that pattern, so we can perhaps plan to implement the documentation update earlier (our releases are typically on a Friday morning), so it is picked up and avoids this kind of lengthy outage. 

Alternatively, if the re-indexing is only performed with the release in the following schedule, then we may have to try to deliver our updates on these dates to catch the re-index, rather than when our release actually goes in

**Comment by sfiserv** [comment]
@StevenPorterFiserv : Devstudio team had already proposed about adding the content on a preview branch, which did not work for your team. https://github.com/Fiserv/Support/issues/316

Hence for now reindexing the Prod env is the agreed work around. FV- Emea team members are already aware of the Production deployment schedules (also shared on the Teams- Status Channel). https://teams.microsoft.com/l/channel/19%3ad7222fe0adde4389b4bd89623202202e%40thread.tacv2/Status?groupId=982cd560-8afd-42fc-bb4c-543e1989b6b1&tenantId=11873a1f-4c8d-450d-8dfb-e37a2e2557f8

In case Devstudio is unable to have a scheduled prod deployment, it is always conveyed to all the tenants in the status channel however we do run the reindexing jobs on that day, so tenants are not blocked on their content updates.

Please reach out to us if you have more questions/concerns.

**Comment by shubhamKanse99** [comment]
Hi, @sfiserv , We have already moved our changes to preview branch for our future releases. 

but we were unable to ask client to refer to the preview branch as here as well we were unable to see swagger. 
Today we are able to see 23.09, but 23.08 next release is still not rendered.

![image](https://github.com/Fiserv/Support/assets/117971606/287faa26-d7a0-4137-8697-25c38838f8a8)


I was aware of the release DevStudio team follows, but i was in the impression that it should pick latest changes when you have the release not discard the existing changes right when I update the main branch. 

from now on, we will update the swagger file at the time of the developer studio deployment.

**Comment by sfiserv** [comment]
@StevenPorterFiserv  please the below screenshot from the Production env, for the preview branch. I can see the content displaying.

> <img width="1638" alt="image" src="https://github.com/Fiserv/Support/assets/87097017/5582fb6a-71d0-47a9-8fd9-a34fb2c515bb">
