### ISSUE TITLE
White Screen Issue

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/Support#475]
**Region (if applicable)**
LATAM

**Page**
[First Vision LATAM](https://developer.fiserv.com/product/FirstVisionLATAM/api/?type=put&path=/account/v2/balance&branch=preview&version=1.2.0)

**Describe the bug**
When I try to expand all the fields on the Request Schema the screen turns white no matter the times I try it never shows all the fields

**To Reproduce**

1. Select Preview version

2. Select API "Balance Update (Cash-in & Cash-out)"

3. Select Request Schema

4. Select Expand All

5. See error

**Screenshots**

![image](https://github.com/Fiserv/Support/assets/111396588/81e7b481-addd-409d-b0c2-64895cbe0e8f)

**Comment by sfiserv** [comment]
@minh-pham1  can you please look into this issue.

**Comment by minh-pham1** [comment]
Hi Cinthya! We've created a ticket for us to investigate and hopefully fix the issue within the next sprint. I'll post more updates here as we progress!

**Comment by sfiserv** [comment]
Issue is tracked in https://firstdatateam.atlassian.net/browse/PORT-7359

**Comment by AnabelCristinaMoreira** [comment]
Hi!
I checked the YAML here and didn't see any problem. If there was any I believe the [Swagger Editor](https://editor.swagger.io/) was going to point it out.
Could this problem be something related to the fact that the "metaData" contains a lis of objects?
<img width="590" alt="image" src="https://github.com/Fiserv/Support/assets/139910463/23ae55d5-c022-4e76-9cce-34a2fb635cde">

**Comment by minh-pham1** [comment]
Hm I don't believe so since the ResponseSchema for `account/wallet-priority-order` also has a list of objects (in this case, `WalletPriorityOrderUpdateRequest.WalletPriorityData` I believe) which is rendering fine when expanded. If it's different then I can look more into it.

I feel like maybe this codeblock might be causing an issue
```markdown
example:
        id: 1
        value: ALPHANUMERIC DATA 1
```

For most of the other parameters/objects I see, the example is listed as underneath the variable that needs it. Maybe this is the issue? Again, I'm not sure so thank you for your help in debugging the issue.

**Comment by AnabelCristinaMoreira** [comment]
I don't know much about front-end but I've tried to see what is showing in the console when I try to expand MetaData and it's throwing this two errors (they are the same):
![image](https://github.com/Fiserv/Support/assets/139910463/248f50ef-60d1-4b5d-895e-7bf8b4bebda5)
I clicked in the link to see the full description and it leads me to [this page](https://legacy.reactjs.org/docs/error-decoder.html/?args%5B%5D=object%20with%20keys%20%7Bid%2C%20value%7D&invariant=31).
<img width="568" alt="image" src="https://github.com/Fiserv/Support/assets/139910463/b0d21d0f-5d45-4ed5-9c6b-16a2a8b86acf">

That's why I still think it's something related to having a list of objects, but I don't know :(

**Comment by AnabelCristinaMoreira** [comment]
The YAML is not created manually that's why I don't really see how this could be the problem.

**Comment by minh-pham1** [comment]
Hi Anabel. Yes I see the same error and have been digging into it. After some more debugging, I'm 100% sure that it's related to this object.
![Screenshot 2023-09-26 at 12 02 24 PM](https://github.com/Fiserv/Support/assets/114534554/f87bb8f1-ec64-4317-b7bd-4542ad524207)

So normally, most properties have their example defined underneath them (not under the entire object). I have a feeling that if you manually made this change in your API reference, it would fix the problem.
![Screenshot 2023-09-26 at 12 02 51 PM](https://github.com/Fiserv/Support/assets/114534554/44f9f420-e5f0-4cdf-897c-86ff208f1cc1)

However, after some research I do see that objects can define their example as an array (like the way it is currently set up). I can adjust the code as well to properly parse for this case as well. I'll test it out and let you know when it moves up to the QA environment.

**Comment by AnabelCristinaMoreira** [comment]
Oh, I see! I will try to modify this manually and see if it's going to fix the problem. Thank you!

**Comment by minh-pham1** [comment]
In this case, I see that in our code the `memoLine` array does receive the array of examples `{id: 0, value: 'ALPHANUMERIC DATA 1'}`. However, we don't really have a definition to show examples for arrays so that's what was causing this issue. It's good that we dug deeper and figured it out.

However, with this definition of examples, I do see that the array objects (id and value) have their default values filled in but _not_ the "_example: ALPHANUMERIC DATA 1_" field like other request parameters.
![Screenshot 2023-09-26 at 12 28 28 PM](https://github.com/Fiserv/Support/assets/114534554/75882bef-2f2b-438b-8ed2-3a616e863d1e)

**Comment by AnabelCristinaMoreira** [comment]
Perfect, thank you so much for your help!

**Comment by minh-pham1** [comment]
The change is now on our qa environment if you would like to validate! Thank you for your patience.

**Comment by AnabelCristinaMoreira** [comment]
It looks like it's working! Thank you! 
<img width="395" alt="MicrosoftTeams-image" src="https://github.com/Fiserv/Support/assets/139910463/6d8f12b6-9e0f-4ba3-9656-48905d2b13ce">
