### ISSUE TITLE
[BUG] - Enum is showing blank

### ISSUE THREAD

**Issue by AnabelCristinaMoreira** [Fiserv/Support#521]
### Product

FirstVision LATAM

### Page

https://developer.fiserv.com/product/FirstVisionLATAM/api/?type=post&path=/account/v2/instantCard&branch=main&version=1.2.0

### Description

When the enum is set as "0,1", it's showing empty in Developer Studio.

I could verify this behavior in two different endpoints, but I assume is a general issue.

**[Customer Update- Request](https://developer.fiserv.com/product/FirstVisionLATAM/api/?type=put&path=/customer/&branch=main&version=1.2.0)**
- Code: 
![image](https://github.com/Fiserv/Support/assets/139910463/9b06db9a-b093-4814-b8d2-a0a8ad61544c)
- Developer Studio
![image](https://github.com/Fiserv/Support/assets/139910463/640fc564-ba2a-4c04-9f89-572a2496db11)

**[Instant Card Add - Request](https://developer.fiserv.com/product/FirstVisionLATAM/api/?type=post&path=/account/v2/instantCard&branch=main&version=1.2.0)**
- Code:
![image](https://github.com/Fiserv/Support/assets/139910463/569c72cb-773b-41d1-b32b-a2c6d7844ca0)
- Developer Studio:
![image](https://github.com/Fiserv/Support/assets/139910463/190f3033-b053-4e36-9832-c8f59782b4f6)

Note that, in the second example, the enum that contains "Y,N" works fine.

Both examples contains "0,1" as a value that should appear.

### Expected Behaviour

Enum showing the values defined in the code.

### Operating system

Windows

### Browser

Google Chrome

**Comment by minh-pham1** [comment]
Hm is the auto-generate schema on Github controlled by you, github, or us? I'm not sure about this from the GIthub side but it looks like it's not properly creating the fields that you expect. For the ones with numbers, I see in the reference yaml that is is being defined as such:
![Screenshot 2023-09-26 at 4 30 01 PM](https://github.com/Fiserv/Support/assets/114534554/dd2dab78-375a-47f0-b80f-acbf07205331)

Which would explain why nothing shows up. Strangely enough, the `accountCreateFlag`'s enum does get properly generated in the Github yaml.
![Screenshot 2023-09-26 at 4 31 36 PM](https://github.com/Fiserv/Support/assets/114534554/0c3071d5-c401-4f22-be53-ecfb264d95f7)

So the issue is most likely somewhere between your code to generate the yaml and the yaml being created on Github itself rather than DevStudio. Is this something that you'll need help with fixing? For now, it would be a manual fix on Github for this API but it is pretty tedious. I'm very not acquainted with the Github side of creating yaml and things of the such.

**Comment by AnabelCristinaMoreira** [comment]
Oh, I see now. I tried to create another another YAML and I am having the same issue so I agree it isn't something related to DevStudio. Thank you for your help!
