### ISSUE TITLE
Internet Payment Gateway (IPG) NA API Explorer not working

### ISSUE THREAD

**Issue by paulohenriqu** [Fiserv/Support#549]
### Product

Internet Payment Gateway (IPG) NA

### Page

https://developer.fiserv.com/product/IPGNA?branch=main

### Description

When I go to the IPG documentation page I aways get the following warning:
 `We are unable to get the list of apis at the moment. Please try again.`
 
 And cannot view any version of the API

### Expected Behaviour

The API explorer should show the endpoints and resquest/response models

### Operating system

macOS Ventura 13.6

### Browser

Google Chrome Version 118.0.5993.117

**Comment by sfiserv** [comment]
@paulohenriqu  IPG na team had pushed changes to the Main branch in github which corresponds to the Production env UI.
DevStudio has to reindex in order to reflect the changes.
To reindex in Prod we need a change request which needs approval from security team. 
currently there is a orgwise freeze going on which is leading to the bug you are seeing in the Prod

cc: @pavelbelousov

**Comment by sfiserv** [comment]
@paulohenriqu  IPG na team had pushed changes to the Main branch in github which corresponds to the Production env UI.
DevStudio has to reindex in order to reflect the changes.
To reindex in Prod we need a change request which needs approval from security team. 
currently there is a orgwise freeze going on which is leading to the bug you are seeing in the Prod

cc: @pavelbelousov

**Comment by sfiserv** [comment]
@pavelbelousov we have fixed the problem in the production. Hence closing this issue.
