### ISSUE TITLE
Uploaded content for TN not reflected in QA devstudio 

### ISSUE THREAD

**Issue by RockReshma28** [Fiserv/Support#582]
### Product

Transfer-now

### Page

TN UI Customization Guide, TN UI Rendering Options

### Description

List of pages:
1.Home>Financial Institutions>Transfer Now>Documentation>TransferNow UI Widget>TN UI Customization Guide
2.Home>Financial Institutions>Transfer Now>Documentation>TransferNow UI Widget>TN UI Rendering Option

### Expected Behaviour

Content should be reflected

### Operating system

Windows Microsoft 365

### Browser

Google Chrome Version 119.0.6045.160 (Official Build) (64-bit)

**Comment by sfiserv** [comment]
we have refreshed the QA env. your content should be reflected now. please check.
Please use the teams channel to inform us if the content is not reflected, instead of creating a github issue. Things get resolved faster via teams channel.

https://teams.microsoft.com/l/channel/19%3a65e0590efd7f4f1294553542e1b9a742%40thread.tacv2/Feedback%2520and%2520Help!?groupId=982cd560-8afd-42fc-bb4c-543e1989b6b1&tenantId=11873a1f-4c8d-450d-8dfb-e37a2e2557f8
