### ISSUE TITLE
Integrate "VerifyNow" with Credit Union, Large Financial Institutions & FinTech

### ISSUE THREAD

**Issue by ManiBharathiNatarajan** [Fiserv/Support#594]
### Context

Integrating VerifyNow with other **Financial Institutions (Credit Union & Large Financial Institutions) & FinTech** to enhance the functionality. 

### Solution

By Integrating VerifyNow with All Financial Institutions & Fintech, users will get benefit from a unified platform.
<img width="193" alt="image" src="https://github.com/Fiserv/Support/assets/153706962/09dd884e-8f8e-4f0a-9e11-6cc5136abc08">
<img width="194" alt="image" src="https://github.com/Fiserv/Support/assets/153706962/be2e7f77-14bf-4363-8b24-e649c43b9542">
<img width="182" alt="image" src="https://github.com/Fiserv/Support/assets/153706962/153c13de-453e-47ad-8f63-b64a0dc73266">

### Alternatives

--

**Comment by minh-pham1** [comment]
Hello Mani, the change has been made and will be reflected on the QA environment in the coming week. Thank you!

**Comment by ManiBharathiNatarajan** [comment]
Hi @minh-pham1 Noted!. Thank you for the update.

**Comment by ManiBharathiNatarajan** [comment]
Hi @minh-pham1 Integration of VerifyNow with other FI's is reflected, but still under FinTech VerifyNow is not reflecting. Can you pl check and update.
<img width="960" alt="image" src="https://github.com/Fiserv/Support/assets/153706962/56845b78-2f98-4624-bb70-354365f9865c">

**Comment by minh-pham1** [comment]
Hello Mani. Sorry I forgot to mention that you'll need to update your Github `tenant.json` - `solutions` field to include fintech. The format should be

```
"solution": ["financial-institutions", "fintech"]
```

Please be sure to apply this change to all relevant github branches for your tenant to reflect on all the appropriate environments. I believe that the scripts needed on my end should already be in place. Please be aware that since our tenant data is cached, you won't see the change for about 48 hours. If needed more urgently, please let me know and I can contact our DevOps team to see whether we can manually reset the cache.

**Comment by ManiBharathiNatarajan** [comment]
Hi @minh-pham1, VerifyNow is now integrated with All the FI's and Fintech. 
<img width="960" alt="image" src="https://github.com/Fiserv/Support/assets/153706962/48d0cfb4-dd76-4da0-8294-6babfc8d0785">
Hence, Closing this ticket.
