### ISSUE TITLE
Rename or Replicate Tenant 'Helix' to 'Vision'  in non-prod

### ISSUE THREAD

**Issue by chunglam65** [Fiserv/Support#639]
### Context

I would like Helix renamed to 'Vision'

### Solution

replace 'Helix' as the tenant and left hand selection. Also, change YAML references

### Alternatives

n/a

### Region

EMEA - global

**Comment by sfiserv** [comment]
Tracking this issue as part of Sprint5 in  https://firstdatateam.atlassian.net/browse/PORT-10051

**Comment by new-to-java** [comment]
After the tenant name change, when I click on Vision (https://qa-developer.fiserv.com/product/vision), it looks like it is being redirecting to FirstVision - APAC. Please check.

![image](https://github.com/Fiserv/Support/assets/106712556/0aa3987a-7171-44c1-8b04-720ac62e01d2)

**Comment by OZ-FS** [comment]
Fixed in dev & qa
<img width="750" alt="Screenshot 2024-03-11 at 2 50 41 PM" src="https://github.com/Fiserv/Support/assets/92183615/982e1bb1-4cb0-4367-a214-e4cf61a30015">
<img width="1070" alt="Screenshot 2024-03-11 at 2 50 52 PM" src="https://github.com/Fiserv/Support/assets/92183615/be19a2c9-69b5-41fc-974e-a68ce637cb23">
<img width="675" alt="Screenshot 2024-03-11 at 2 51 18 PM" src="https://github.com/Fiserv/Support/assets/92183615/7b472c79-8112-4e6f-9d1a-c37a65c720a4">

**Comment by OZ-FS** [comment]
@new-to-java  please verify

**Comment by OZ-FS** [comment]
Please note the URL 
https://dev-developer.fiserv.com/product/Vision?branch=develop
https://qa-developer.fiserv.com/product/Vision?branch=develop

**Comment by sfiserv** [comment]
@chunglam65 closing this issue as it is completed as per this request and will rework on the product name once we receive a new request.
