### ISSUE TITLE
Text in callout blocks not visible in dark mode

### ISSUE THREAD

**Issue by rholstad** [Fiserv/Support#643]
### Page

Throughout

### Description

When using a browser in dark mode, the blocks of text used for notes or callouts are not visible because the background and text are both white.

![Screenshot 2024-03-14 at 9 46 54 AM](https://github.com/Fiserv/Support/assets/10248237/159d87f9-32e2-4d5b-a835-a2a95f1f2054)

### Expected Behaviour

Either the text color should _not_ be dynamic based on the appearance mode of the browser, or the background of these text blocks _should_ be dynamic based on the appearance mode of the browser.

### Operating system

macOS Sonoma 14.2.1

### Browser

Google Chrome Version 122.0.6261.94

**Comment by minh-pham1** [comment]
Hello @rholstad!

Thanks for bringing this to our attention. This issue has already been identified and fixed on our `qa` environment so it will be rolling up through our deployment schedule to stage and production within the next 2 weeks. If you'd like, please feel free to validate your document on the `qa` environment to see if this issue is still pertinent on any of your other documents.

Apologies for the inconvenience!

**Comment by minh-pham1** [comment]
Marking as complete due to inactivity and work being done on our side.
