### ISSUE TITLE
Need to Change Application Name in Dev Studio (All Environments )

### ISSUE THREAD

**Issue by paulmohljr** [Fiserv/Support#649]
### Context

Would like to change "ConnectPay" name in env.developer.fiserv.com to "PaybyBank"

### Solution

change "ConnectPay" name in env.developer.fiserv.com to "PaybyBank"

### Alternatives

None

### Additional Context

No

### Region

US

**Comment by paulmohljr** [comment]
Do you want your product name to be updated to Pay by Bank as well? Or just the url to change to env.developer.fiserv.com/product/PaybyBank? **YES**
Do you want to rename your github repository? This process might take a bit longer due to various caches and your product might not show up on our UI briefly (though it shouldn't be longer than one day).**YES**
Please also make sure to rename your product in config/tenant.json accordingly.**Will do when i get word on when this will be done.**

**Comment by minh-pham1** [comment]
Ok noted, thanks for the quick response! I have assigned the ticket to a developer, though since we're in about to finish up with this sprint it'll be slated for next sprint. In that case, the change will take effect on our `qa` environment in 3 weeks. I'll be sure to keep you updated! Thank you.

**Comment by minh-pham1** [comment]
I made the Pull Requests necessary to update the product name and title for you on the Github. Please feel free to check and merge at your convenience.

**Comment by minh-pham1** [comment]
Hello @paulmohljr! Just one last confirmation for your name, title (used in URL), and github repo name.

- Name: `Pay by Bank`
- Title: `PaybyBank` -> `https://qa-developer.fiserv.com/products/PaybyBank`
- Github: `pay-by-bank`

Are these fields ok? Just want to finalize the changes and make sure everything is as expected.

**Comment by paulmohljr** [comment]
those work for me

**Comment by minh-pham1** [comment]
Hello @paulmohljr! Sorry for the late update. Since `qa` has been deployed, we have updated your product name to `Pay by Bank` and github to https://github.com/Fiserv/pay-by-bank as requested! Please validate and feel free to close this ticket if there is no other ask for this ticket.

Please note the promotion to `stage` and `production` will happen at a later time and I have taken into account the name change. If you'd like, you can technically keep this open for that reason but otherwise I'll update #655 once it happens. Thank you for your patience!

**Comment by russnicoletti** [comment]
Hi @paulmohljr, we noticed your `docs/getting-started.md` file looks like it needs an update. The last sentence is incomplete. It is "If you have any questions please reach out to". If you have any questions, please let me know. Thanks.
