### ISSUE TITLE
Problems redirecting to external links in PROD env - Issuer Solutions

### ISSUE THREAD

**Issue by eliascanaza** [Fiserv/Support#666]
In Developer Studio for external links, in Issuer solutions we do have 3 buttons to send us to external links, when we are clicking over those is showing us an popup, but if we select "Do not show this again" in the next time is doing nothing, please follow this steps to replicate the issue:

1. Go https://developer.fiserv.com/product/IssuerSolutions
2. Click API Search button (Mark checked "Do not show this again")
3. Click Follow Link (Its opening new tab with external link)
4. Click again in API Search button
5. Its doing nothing.

![image](https://github.com/Fiserv/Support/assets/1819754/81fc4759-fd13-427e-a803-e4e2cfa13b65)

**Comment by minh-pham1** [comment]
Hello @eliascanaza! Thanks for catching this issue, we have replicated it and are working on a fix. We'll update and let you know whether this will be hotfixed up to our production environment or simply follow our normal deployment cycle.

While it is inconvenient, I do believe that the user can still right click to perform the various URL functions such as `Open in new tab` or `Copy link address` to still access the page as usual.

**Comment by minh-pham1** [comment]
Hello! Just an update, we have identified and applied a fix on our `dev` environment. Due to the severity, we are also going to hotfix it up until `stage`, with the issue being slated to be fixed on `prod` on our regular deployment schedule this Thursday 4/4. We'll update as we get closer to the date if it is not possible.

In the mean time, please note that while our redirection modal opens a new tab when the user clicks on `Follow link`, if you want your link to continue opening in a new tab (probably preferred) then you'll want to add `target="_blank"` to your <a> tag.

Ex: `<a href="https://qa-fiapi.firstdata.com/portal/NA/search" class="fw-bold btn btn-fiserv">API Search ></a>` -> `<a href="https://qa-fiapi.firstdata.com/portal/NA/search" class="fw-bold btn btn-fiserv" target="_blank">API Search ></a>`

**Comment by minh-pham1** [comment]
Hotfix is now up to our `qa` environment. I also saw that you made the `target="_blank"` change and it looks good to me!

**Comment by eliascanaza** [comment]
I tested in QA environment and its working as expected, please lets have this in stage env.

**Comment by minh-pham1** [comment]
Quck update: Our `stage` deployment has completed and this issue has been fix. Please feel free to validate and let us know if there are any other issues there.

**Comment by eliascanaza** [comment]
I testes in Stage/CAT environment and the button with external links are working as expected, the only issue I found the sandbox is failing
![image](https://github.com/Fiserv/Support/assets/1819754/37e2aaff-b6ea-47e0-afc7-a660d29c431d)

**Comment by minh-pham1** [comment]
Production deployment has been completed and the issue regarding external link redirection failing should now be fixed. Please verify! Thank you for your patience.

**Comment by eliascanaza** [comment]
this issue is already solved, thanks.
