### ISSUE TITLE
Enable run request for CashFlowCentral

### ISSUE THREAD

**Issue by mhaar-finact** [Fiserv/Support#673]
Please enable run request for CashFlowCentral via Prism Mock Server.

**Comment by minh-pham1** [comment]
Hello @mhaar-finact! This is actually controlled on your end via Github under your `tenant.json` configs for the field `product.feature.sandBox` which you can set to true if you would like to use the Prism Mock Server. If this is true, the `Run Request` on the API Explorer should be enabled.

Please note that there may be some TTL for various config caches which may prevent this from being active immediately. However, it should be active after a day, otherwise feel free to mention the issue in this ticket and I'll take a look.

**Comment by minh-pham1** [comment]
Created PR at https://github.com/Fiserv/cash-flow-central/pull/7, please review the change and change as needed, merging whenever you would like. Thank you!

**Comment by minh-pham1** [comment]
PR has been merged. Please validate that the run request is now active for your product.

**Comment by minh-pham1** [comment]
Closing as ticket's request has been completed.
