### ISSUE TITLE
Stage Portal getting Authentication Required 

### ISSUE THREAD

**Issue by RONAKPATEL6178** [Fiserv/Support#674]
### Product

FirstVision - APAC

### Page

https://stage-developer.fiserv.com/product/FirstVisionAPAC?branch=stage

### Description

while try to open stage portal from Microsoft edge getting authentication required. can you please check.
URL: https://stage-developer.fiserv.com/product/FirstVisionAPAC?branch=stage
for a reference snapshot attached below. 
![image](https://github.com/Fiserv/Support/assets/136304957/a27a2a68-32f4-42b4-a923-eb78a3fdbe49)

### Expected Behaviour

 https://stage-developer.fiserv.com/product/FirstVisionAPAC?branch=stage
 as per image  mention here expected result will be as shown in snapshot.
![image](https://github.com/Fiserv/Support/assets/136304957/bcfd2413-ad29-4382-aeb1-60ec47d2a641)

### Operating system

Windows 

### Browser

Microsoft Edge 

### Region

Version 123.0.2420.97

**Comment by minh-pham1** [comment]
Hello @RONAKPATEL6178! Due to a new security policy, basic auth (which we have always used) has been disabled on Windows machine.

If you still have the auth information or URL with the auth username+password, please use Firefox as a temporary fix. I believe you should still be able to access the site on Windows with Firefox according to what some other users have reported.

The team is in contact with Cyber for alternative solution or potentially whitelisting. Apologies for the inconvenience!
