### ISSUE TITLE
Access Code applied Issue in Banking Hub workspace

### ISSUE THREAD

**Issue by AjitR01** [Fiserv/Support#676]
### Product

Banking Hub

### Page

https://developer.fiserv.com/workspaces

### Description

When a user attempts to apply an access code to retrieve app credentials, an error occurs stating "access code applied", preventing further progress. This issue is currently booking clients from accessing the workspace. 

![image](https://github.com/Fiserv/Support/assets/137955475/132c3cad-1f8b-439b-97e6-8d09ffc682b8)

Transaction ID:
e0bf11ed-6052-415c-8631-8005a08b9569

### Expected Behaviour

When user applies the access code it should work without error.

### Operating system

Windows

### Browser

Chrome

### Region

Production environment

**Comment by minh-pham1** [comment]
Hello @AjitR01, we'll investigate this issue ASAP. Our team member may take a while to get an access code and investigate logs for replication of issue. Greatly appreciate including the `Transaction ID` of the error you got, this will greatly assist our efforts.

I'll keep this issue updated as we progress. Thank you for your patience.

**Comment by minh-pham1** [comment]
Quick update: We already have a fix for this issue, it is related to the apiProduct `AM-BH-CORE-VAL_CERT` causing an error due to some character parsing issue on our backend. The fix is already on our Sprint 7 (currently on `stage` environment) and will be going to `production` next week.

However, I will discuss with our manager regarding escalating this issue as needed and whether we need to open an emergency change request to hotfix to production earlier. Thank you for your patience.

**Comment by minh-pham1** [comment]
Quick update: We have discussed with our manager and devops team. Unfortunately, the emergency CR would take too long and add a lot of burden on them (along with our existing changes as required by Cyber for various other security implementations). As such, we'll deploy the changes to fix this issue on Thursday along with our regularly scheduled production deployment.

If possible, please provide the customer/user in question with the API Key manually for the time being. We recognize that this is inconvenient and the isue should be rectified soon. Thank you for understanding.

**Comment by minh-pham1** [comment]
Issue should now be fixed. Please feel free to reopen ticket if there is still an issue.
