### ISSUE TITLE
Move PaybyBank from Stage to Prod

### ISSUE THREAD

**Issue by paulmohljr** [Fiserv/Support#677]
### Context

Need to migrate and display PaybyBank in production in Developer Studio

### Solution

Ability to see PaybyBank Dev Studio production 

### Alternatives

None

### Region

Production - US

**Comment by minh-pham1** [comment]
Hello @paulmohljr! As previously discussed, you were slated to go to production with our Sprint 7 code changes. This will occur this week Thursday (4/25) as per our usual deployment schedule barring any technical issues. It's good to have this Issue to have tracking and allow us to comment on it though, so thank you!

As a reminder, please make sure to update your github `main` branch with the proper documentation, configs, and APIs as needed to have everything ready to be displayed on production since we will deploy the changes to promote and index everything at the same time.

Thank you!

**Comment by minh-pham1** [comment]
Hello! We have promoted your product to prod. We did see that you did not push any updated configs/documents onto your Github main branch and did it this time but please take a moment to validate that everything there is as you expect. Thank you!

**Comment by minh-pham1** [comment]
Closing issue as work is completed. Please feel free to reopen the issue or request additional help via a new Issue or Teams message as needed!
