### ISSUE TITLE
How to run IssuerSolutions api what is the baseUrl ?

### ISSUE THREAD

**Issue by mtariqsajid** [Fiserv/Support#690]
### Product

IssuerSolutions

### Page

Dev

### Description

hi i want to know how to run the IssuerSolutions api, i cannot find the baseurl of the IssuerSolutions dev environment.

I try this baseURL:  https://cat.api.firstdata.com/fs

but receiving this error

```js
{
    "errorMessage": "Requested API resource path does not exist. Please review Fiserv API documentation at 'https://developer.fiserv.com/merchants'.",
    "errorCode": "404 - Not Found"
}
```

{{baseUrl}}/merchantViews/v4/merchantCardTypeTransaction

### Expected Behaviour

api response should come

### Operating system

Ubuntu 22.04 LTS

### Browser

Google Chrom 122.0

**Comment by yanyan-cathy** [comment]
@eliascanaza Could you please help with this issue for the baseURL? Thanks!

**Comment by minh-pham1** [comment]
As noted by Cathy, we only provide the documentation/spec for the APIs along with a Prism mock server to execute them on our own servers. In order to execute the APIs with Issuer Solutions, you'll need to talk to Elias or another point of contact on their team to get the endpoint, proxy, API key, and/or any other configurations needed to utilize their endpoints.

**Comment by eliascanaza** [comment]
Hi @mtariqsajid we do have a sandbox simulator in Developer Studio for Merchants https://developer.fiserv.com/product/IssuerSolutions/api/?type=post&path=/merchant/v1/merchantBlockNotificationAdd&branch=main&version=1.0.0

you can take a look but if you need access to those APIs you need to contact to Sales Department for more detail.

**Comment by minh-pham1** [comment]
Closing as solution seems to have been provided and no further inquiry was posted.
