### ISSUE TITLE
Add User-Agent Header to PaymentJS Webhook

### ISSUE THREAD

**Issue by banengc** [Fiserv/Support#707]
### Context

Our service provider has a standard WAF rule that blocks requests which don't have a User-Agent header; which results in the webhook response being blocked since it doesn't have that header. While we ask them to change said rule whenever it pops up, we would like to see if it was possible to get a permanent fix on this end.

### Solution

Add in a User-Agent header to the PaymentJS webhook response

### Alternatives

Modify WAF rules temporarily

**Comment by OZ-FS** [comment]
Could you please provide additional information about this request.
If the issue is with Dev Studio: please specify the particular page, product name, doc path, api type/path.
If the issue is with an endpoint of a specific product you are using: product name, api type/path.
In later case, we can provide the point of contact if we know who's product you are using.

**Comment by banengc** [comment]
This is for the First Data Gateway (I believe it might also be called IPG). Documentation here: [https://docs.paymentjs.firstdata.com/#overview](https://docs.paymentjs.firstdata.com/#overview). Unfortunately the nature of PaymentJS obfuscates what the actual endpoint is (as it is client-side) but it should be similar to https://prod.api.firstdata.com/gateway/v2/

**Comment by OZ-FS** [comment]
Internet Payment Gateway (IPG) NA point of contact are andrew.spikin@fiserv.com & vijay.chavan@fiserv.com

**Comment by banengc** [comment]
ok, thank you
