### ISSUE TITLE
Stage-Developer DevStudio does not reflect latest merged code

### ISSUE THREAD

**Issue by AbhiNaikoti** [Fiserv/Support#721]
### Product

Pay By Bank

### Page

Home -> Merchants -> Pay by Bank -> Purchase/Void/Refund/Capture/Authorize

### Description

Changes were made to the openapi.yaml file in the Fiserv/Pay-by-bank repository, these changes were then merged into develop: https://github.com/Fiserv/pay-by-bank/pull/151
When we wanted to test our changes in stage-developer.fiserv.com url, our latest changes were not reflected. 

### Expected Behaviour

The changes made in the openapi.yaml file need to be reflected in stage-developer.fiserv.com

### Operating system

macOS Sonoma 14.5

### Browser

Google Chrome Version 119.0.6045.123

### Region

US - North East (NJ)

**Comment by minh-pham1** [comment]
Hello Abhi, as per our usual process, in order to propagate your work up to DevStudio upper environments such as `stage` and `prod`, you'll also need to merge those changes on your Github repository to the `stage` and `main` branch respectively. Here is the mapping for your convenience.

Example: DevStudio_Env -> Github_Branch
- qa-developer.fiserv.com -> `develop`
- stage-developer.fiserv.com -> `stage`
- developer.fiserv.com -> `main`

For content refresh on every environment
- configs and MD: Within 1 hour
- API spec: 
  - QA: Every 2 hours
  - Stage: Once a day
  - Prod: Twice a day

**Comment by AbhiNaikoti** [comment]
Hello Minh,

Thank you for the information.

Best,
Abhi Naikoti

From: Minh Pham ***@***.***>
Date: Tuesday, July 2, 2024 at 12:58 PM
To: Fiserv/Support ***@***.***>
Cc: Naikoti, Abhishek (Berkeley Heights) ***@***.***>, Author ***@***.***>
Subject: Re: [Fiserv/Support] Stage-Developer DevStudio does not reflect latest merged code (Issue #721)

  ⚠ EXTERNAL MESSAGE – Think Before You Click


Hello Abhi, as per our usual process, in order to propagate your work up to DevStudio upper environments such as stage and prod, you'll also need to merge those changes on your Github repository to the stage and main branch respectively. Here is the mapping for your convenience.

Example: DevStudio_Env -> Github_Branch

  *   qa-developer.fiserv.com -> develop
  *   stage-developer.fiserv.com -> stage
  *   developer.fiserv.com -> main

For content refresh on every environment

  *   configs and MD: Within 1 hour
  *   API spec:

     *   QA: Every 2 hours
     *   Stage: Once a day
     *   Prod: Twice a day
