### ISSUE TITLE
Catalog Search Capabilities

### ISSUE THREAD

**Issue by kcaramat** [Fiserv/Support#724]
### Context

Can the Catalog Search capabilities be expanded up to also pull up the same results as the Search Section within Dev Studio?

### Solution

Can the Catalog Search capabilities be expanded up to also pull up the same results as the Search Section within Dev Studio?

### Alternatives

Can the Catalog Search capabilities be expanded up to also pull up the same results as the Search Section within Dev Studio?

**Comment by minh-pham1** [comment]
Hello! As per our design and architecture, the Catalog page is intended for users who do not have a clear goal/point-of-contact to be able to scroll through an infinite list of APIs (filtering as they get a better idea) just as they would browse a phone book.

Unfortunately, having an infinite list with every product's `Getting started` and `How to use our API` document listed in a row would not be very helpful for our users since they're not very descriptive/distinct from each other to provide users with a better pathway. Developer Studio is first and foremost a platform for hosting APIs and helping customers find the exact APIs they need, test it using our explorer, and read documentation for additional information as they move forward with integrating with a specific team.

As such, I don't believe that we will want to implement this feature. Please let me know if you have any thoughts or suggestions on this topic and I can forward it to our team and manager. Thank you!

**Comment by kcaramat** [comment]
Hi Minh, this request and feedback was received from new Dev Studio users with the launch of our new Direct Platform Specifications tenant space. They navigated to the Dev Studio Home page and couldn't figure out how to get back to the Direct Platform Specifications tenant space. They went to Catalog and searched a specification (ISO8583 Global) they frequently use and nothing came up. It would be helpful if the Direct Platform Specifications Product pulled up in the results since this a specification within the tenant space.

**Comment by minh-pham1** [comment]
In that case, I believe that most users would instead use the `Search` feature since they're specifically searching for something. However, we are in an ongoing effort to collect and analyze user usability data to better improve user experience so we do appreciate this feedback and example. I'll forward it to our product manager! Thank you.

**Comment by kcaramat** [comment]
Thanks for the update and insight!
