### ISSUE TITLE
Enable sandbox for Global Currency Solution(OpenFX)

### ISSUE THREAD

**Issue by prashantkumarfiserv** [Fiserv/Support#725]
We want to enable sandbox for Global currency solution. Please help us with steps and timelines

**Comment by minh-pham1** [comment]
Hello Prashant, I see that you already have the API explorer along with some API yamls published. In order to enable the sandbox mock run request feature, all you have to do is go to your github -> `config/tenant.json` -> change the field `product.feature.sandbox` value to `true` and it should enable it!

**Comment by prashantkumarfiserv** [comment]
@minh-pham1  We also want to configure sandbox, let me know the process for that and timelines.

**Comment by minh-pham1** [comment]
I believe we already completed this task via Teams, if that's incorrect please let me know otherwise I can close this ticket.
