### ISSUE TITLE
Deployment to production environment for Silvercore product [Silvercore] [Stage & Prod]

### ISSUE THREAD

**Issue by lucasfiserv1** [Fiserv/Support#727]
After the validation of the Silvercore product in the QA environment and it was found that it is already working stably, its release to the productive environment is requested.

**Comment by lucasfiserv1** [comment]
The first one, I want my tenant to be available in the Dev Studio production environment, but currently my tenant is in the develop branch, I didn't know if I had to move my content to the stage branch or if you would do it.

**Comment by russnicoletti** [comment]
I have investigated and your tenant is available in the Dev Studio production environment. Changes to API specifications in the "main" branch are pushed to Developer Studio twice a day.
![Screenshot 2024-07-26 at 3 46 49 PM](https://github.com/user-attachments/assets/bd39f79e-4ad3-4988-a6d2-e0ee901724aa)

**Comment by russnicoletti** [comment]
Closing the request a the SilverCore tenant is in production

**Comment by lucasfiserv1** [comment]
Hi, maybe I expressed myself wrong, I want the changes from the develop branch to be moved to the main branch

**Comment by russnicoletti** [comment]
Hi @lucasfiserv1, in order to merge the changes from the develop branch to the main branch you need to create a "feature" branch with main as the base branch (for example, create a "dev-to-main" branch) . You would then need to merge the changes from the develop branch into the dev-to-main branch. And finally create a pull request for merging dev-to-main into main. If this is unfamiliar to you, there is a lot of helpful information online that should help.

**Comment by lucasfiserv1** [comment]
Hi, I have already merged the develop branch into the main branch and then made the pull request to the source repository. I understand that in approximately 2 days main will be deployed to production, is that correct?

**Comment by lucasfiserv1** [comment]
Hi, I saw that the deployment was done in prod, but I saw an error, I'm going to open another issue for that bug, thanks.
