### ISSUE TITLE
Onboard a new tenant

### ISSUE THREAD

**Issue by KevinMeldau** [Fiserv/Support#734]
### Name of your product / tenant

APEX

### Type of Tenant

Doc only

### Team Members

kevin-meldau–fiserv, fuller-tice–fiserv, lincoln-banry–fiserv

### Bug Reporting

kevin-meldau–fiserv, fuller-tice–fiserv, lincoln-banry–fiserv

### Feedback Reporting

kevin-meldau–fiserv, fuller-tice–fiserv, lincoln-banry–fiserv

### Enhancement Reporting

kevin-meldau–fiserv, fuller-tice–fiserv, lincoln-banry–fiserv

### Internal tenant

No

### Product of Carat

No

### Merchants solution area

No

### Customer Segments for Merchants

- [ ] SMB
- [ ] Enterprise

### Financial Institutions solution area

No

### Customer Segments for Financial Instituitions

- [ ] Bank
- [ ] Credit Union
- [ ] Large Financial Institution

### Fintech solution area

No

### Region of Operation

- [ ] North America
- [ ] EMEA
- [ ] LATAM
- [ ] APAC

### RESTful

No

### SDK

No

### Runbox

No

### Mock Sandbox

No

### Live Server

No

**Comment by minh-pham1** [comment]
Hello! Your Github repository has been created and is accessible at https://github.com/Fiserv/apex for user KevinMeldau, as I was unable to find the other users that were listed.

I did note that this was not marked as an `Internal tenant`. Is that intentional?

It will be onboarded to our Developer Studio `qa` environment in 2 weeks. I'll leave a comment here once deployment is complete. Thank you!

**Comment by KevinMeldau-Fiserv** [comment]
My Fiserv profile is – https://github.com/KevinMeldau-Fiserv

**Comment by KevinMeldau-Fiserv** [comment]
Lincoln – https://github.com/LincolnBanry
Fuller – https://github.com/FTice

**Comment by minh-pham1** [comment]
Invitations sent. You should be able to access and write to the repository once accepted!

**Comment by minh-pham1** [comment]
Product has been onboarded up to `qa` environment.
