### ISSUE TITLE
Looking to render the tables and text blocks as per our requirement rather than giving control to devstudio HTML rendering

### ISSUE THREAD

**Issue by kongaravinatha** [Fiserv/Support#748]
### Context

One of the products names: Fraud Mitigation has some tables where we need to align them to the center of the page and I am not able to do it. Looks like md files are internally rendered as HTML and controlled by Devstudio

### Solution

Pls give us the way to configure either html or Css formatting for the tables, blocks etc which will be good for styling the content.

### Alternatives

One of the Devstudio resource has to know the requirements from each product how they are looking for the tables and text to be aligned.

### Region

Dev, QA, Stage and PROD

**Comment by minh-pham1** [comment]
Our markdown documents do allow you to add HTML elements into the page. Can you try adding span/div with various classNames to help center elements as usual then embed a table element in it?

Unfortunately, we cannot manually adjust or add css otherwise for each individual product's requirement and styling. There are a lot of other products (such as TransferNow, BankingHub, and CommerceHub) who have various customizations in their markdown files which seem to work great.

**Comment by kongaravinatha** [comment]
@minh-pham1 Can you provide me some samples for this ?

**Comment by minh-pham1** [comment]
https://github.com/Fiserv/transfer-now/blob/develop/docs/getting-started/resp-view-transfernow.md?plain=1

**Comment by OZ-FS** [comment]
Would make tables 100% width would work for you?

**Comment by kongaravinatha** [comment]
I want them to be center of the page. Looks like we need to render via HTML ?

**Comment by OZ-FS** [comment]
html & style. Example from https://github.com/Fiserv/transfer-now/tree/develop/docs
