### ISSUE TITLE
Unable to merge the PR because of the validation change

### ISSUE THREAD

**Issue by kongaravinatha** [Fiserv/Support#753]
### Product

Fraud Mitigation

### Page

https://github.com/Fiserv/fraud-mitigation/actions/runs/11056557811/job/30718508582?pr=68

### Description

![image](https://github.com/user-attachments/assets/f7815682-a1dd-4d3b-b38d-5082382d9ad0)

![image](https://github.com/user-attachments/assets/64884b1f-9374-48cd-822b-4d841dadf7e1)

### Expected Behaviour

My PR needs to be approved. I have the product description in my tenant-config.json 

### Operating system

macOS

### Browser

Google chrome

**Comment by minh-pham1** [comment]
Hello! As noted by the validator, your short description is longer than 112 characters (163) hence it is being blocked.

**Comment by russnicoletti** [comment]
Hello @kongaravinatha, the validator change was to 1) ensure there is a description in the product section of tenant.json, and 2) ensure the description in the product section is 112 characters or less (because this description is used in the "mega menu" and it will be truncated if it is longer than 112 characters). See https://teams.microsoft.com/l/message/19:26fd28b4ef154d5da922849cc2f15360@thread.tacv2/1727289796905?tenantId=11873a1f-4c8d-450d-8dfb-e37a2e2557f8&groupId=982cd560-8afd-42fc-bb4c-543e1989b6b1&parentMessageId=1727289796905&teamName=Developer%20Studio%20from%20Fiserv&channelName=General&createdTime=1727289796905

**Comment by kongaravinatha** [comment]
@russnicoletti 
Where can i see the mega menu ? Can you send me the link to see it

**Comment by russnicoletti** [comment]
This is the "menu" you see when you click on "Payments" or "Banking" from the Developer Studio home page. When you click on Payments you'll see that for your product the description is shown as "Detects, prevents, and mitigates fraudulent activities.". That is because this is the short description for your product in the our database. We want to move from having this information in our database to having it in the tenant.json of the GitHub repository so that the product owners have control over that description.

**Comment by minh-pham1** [comment]
<img width="1549" alt="Screenshot 2024-09-26 at 12 50 45 PM" src="https://github.com/user-attachments/assets/aaa882d2-3a2c-4611-86b9-1c747ae6145f">

**Comment by kongaravinatha** [comment]
Thanks for letting me know .
