### ISSUE TITLE
Accessplus - Aus

### ISSUE THREAD

**Issue by tarunfiserv** [Fiserv/Support#757]
### Name of your product / tenant

Accessplus - Aus

### Short Description of Tenant

Accessplus is a techonology rich application suite offering applications addressing multiple aspects of the issuing lifecycle.  Operating in collaboration with FirstVision™, each of the offering provides a well rounded and scalable solution.

### Type of Tenant

Full service

### Team Members

joseph.rajamoni@Fiserv.com, saeel.borkar@fiserv.com, sanjayakumar.pradhan@fiserv.com, tarun.mittal@fiserv.com

### Bug Reporting

joseph.rajamoni@Fiserv.com, saeel.borkar@fiserv.com, sanjayakumar.pradhan@fiserv.com

### Feedback Reporting

joseph.rajamoni@Fiserv.com, saeel.borkar@fiserv.com, sanjayakumar.pradhan@fiserv.com

### Enhancement Reporting

joseph.rajamoni@Fiserv.com, saeel.borkar@fiserv.com, sanjayakumar.pradhan@fiserv.com, tarun.mittal@fiserv.com

### Internal tenant

No

### Product of Carat

No

### Payments solution area

No

### Banking solution area

No

### Fintech solution area

Yes

### Region of Operation

APAC

### Runbox

No

### Mock Sandbox

No

### Live Server

No

### Sales Contact

No

**Comment by russnicoletti** [comment]
@tarunfiserv How would you like the title of your product to appear in Dev Studio: "Accessplus - Aus"? "Accessplus Aus"? Some other variation? I will create the onboarding ticket when you let me know the title you would like. Thanks.

**Comment by tarunfiserv** [comment]
@russnicoletti You can set it up with title "Accessplus - Aus" or "Accessplus - Australia", both will be fine. Here hyphen is used to separate the region from product name.

**Comment by russnicoletti** [comment]
Thanks for the update @tarunfiserv, we will use "Accessplus - Aus" since that is how you originally specified it.

**Comment by minh-pham1** [comment]
Hello! Sorry for the delayed update. Your Github repository is available at https://github.com/Fiserv/accessplus-aus

The product is also accessible on our Developer Studio `qa` environment:
https://qa-developer.fiserv.com/product/AccessplusAus

Please feel free to validate and continue the conversation here or Teams `Feedback and Help` channel if you have any issues. We'll close this ticket in ~2 days if there are no issues with the onboarding. Apologies for the delay once again!

**Comment by russnicoletti** [comment]
@tarunfiserv We were reviewing your product and noticed you specified "Fintech solutions area". Unfortunately, we no longer support that category. In order to help customers find your product on Developer Studio, it would be helpful to categorize your product as being in the **Payments** and/or **Banking** solutions area. Additionally, if in the **Payments** solutions area, you should specify a **customer segment**: either or both SMB or Enterprise, and choose any or all of the following **capabilities**: Analytics, Boarding & Management, Disbursements, Omni-Channel, Value Added Services.

If in the **Banking** solutions area, you can choose any of the following customer segments: Bank, Credit Union, Large Financial Institution, and choose any of the following capabilities: Banking as a Service, Issuing, Licensing, Financial Data Management.

I apologize in advance for asking all these questions. The more information we have regarding your product, the better we can serve our customers. Please let us know if you have any questions. Thanks.
