### ISSUE TITLE
Unable to see the APIs in Stage Environment

### ISSUE THREAD

**Issue by kongaravinatha** [Fiserv/Support#763]
### Product

Fraud Mitigation

### Page

payments --> Fraud mitigation --> API Explorer

### Description

<img width="680" alt="image" src="https://github.com/user-attachments/assets/61c2cc8d-7df5-49da-be41-63b9f9699fab">

unable to see the APIs listed for this product

### Expected Behaviour

We should be able to see all the APIs 

### Operating system

macOS

### Browser

Google chrome

**Comment by minh-pham1** [comment]
Hello Kongara! It seems that you updated the list of api files you're pulling from and deleted the old one. As such, we could not fetch the new files until our API auto-indexes at 8PM PDT.

However, since our DevOps were online looking at `stage` environment in preparation for our deployment, I asked them to index your APIs for you. Please validate and let me know if there's still any issues.
